import Head from 'next/head'
import { useEffect, useState, useContext } from 'react'
import { useRouter } from 'next/router'
import axios from 'axios'

import { AuthContext } from '../../contexts/Auth.Context'

const TeacherLogin = () => {
    const router = useRouter()

    const {auth, setAuth} = useContext(AuthContext)
    const [username, setUsername] = useState()
    const [password, setPassword] = useState()

    const [invalidInput, setInvalidInput] = useState(false)

    const loginUser = (e) => {
        e.preventDefault()
        setAuth({...auth, loading: true})

        console.log('ran')
        axios.post(process.env.NEXT_PUBLIC_BACKEND_HTTP_BASE+'auth/token/', {
            username, password
        }, { headers: {'Content-Type': 'application/json'}})
        .then(res => {
            setAuth({ loading: false, isAuthenticated: true, tokens: res.data, userType: "teacher" })
        })
        .catch(res => {
            console.log('login failed')
        })
    }

    useEffect(() => {
        if (auth.isAuthenticated) router.push('/teacher/')
    }, [auth])

    return (
        <div>
            <Head>
                <title>Login | LMS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mt-8 mx-8">
                { invalidInput && <p className="py-2 px-2 border-2 border-red-500 rounded-lg font-bold text-red-500">Invalid inputs.</p>}

                <h1 className="text-5xl my-6">Login for Teachers</h1>

                <form onSubmit={e => loginUser(e)}>
                    <label>
                        <p>Username:</p>
                        <input className="border-2" type="text" name="code" onChange={e => setUsername(e.target.value)} />
                    </label>
                    <label>
                        <p>Password:</p>
                        <input className="border-2" type="password" name="index" onChange={e => setPassword(e.target.value)} />
                    </label>
                    <br />
                    <button type="submit" className="bg-gray-500 text-white mt-4 py-1 px-2 rounded-lg">Submit</button>
                </form>
            </main>

            <footer>
            </footer>
        </div>
    )
}

export default TeacherLogin
