@startuml
!include <office/Concepts/globe_internet>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Core LOGIC_COLOR
    Class Student_Core LOGIC_COLOR_T2
    Class Accounts MODEL_COLOR
    Class Storage STORAGE_COLOR
}

Class "<$user>" as User MODEL_COLOR_T2

UI -down[UI_COLOR]-> Accounts
UI -[UI_COLOR]-> Core
UI -[UI_COLOR]-> Student_Core
Accounts -[MODEL_COLOR]-> Storage
Core -[LOGIC_COLOR]-> Storage
Student_Core -[LOGIC_COLOR_T2]-> Storage
Storage -up[STORAGE_COLOR].> Core
Storage -up[STORAGE_COLOR].> Accounts
Storage -up[STORAGE_COLOR].> Student_Core
Core -up[LOGIC_COLOR]-> UI
Student_Core -up[LOGIC_COLOR_T2]-> UI
Accounts -up[MODEL_COLOR]-> UI
User -down.> UI
@enduml