import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState, useEffect, useContext } from 'react'
import axios from 'axios'

import { AuthContext } from '../../../contexts/Auth.Context'
import { ClassroomsContext } from '../../../contexts/Classrooms.Context'

import Dashboard from '../../../components/Dashboard'
import Settings from '../../../components/Settings'

const Classroom = () => {
    const router = useRouter()
    const { auth, setAuth, getAccessToken } = useContext(AuthContext)
    const { classrooms, setClassrooms } = useContext(ClassroomsContext)

    const [classroom, setClassroom] = useState()
    const [tasks, setTasks] = useState([])
    const [isDashboard, setIsDashboard] = useState(true)
    const [names, setNames] = useState()

    useEffect(() => {
        const { code } = router.query
        if (!code) return

        if (!classrooms) {
            // Get classroom data if user went directly to classroom link
            getAccessToken().then((accessToken) => {
                axios.get(process.env.NEXT_PUBLIC_BACKEND_HTTP_BASE+'core/classrooms/'+code+'/', {
                    headers: {'Authorization': 'Bearer '+accessToken},
                })
                .then(res => {
                    setClassroom(res.data)
                    setClassrooms([res.data])
                })
                .catch(res => {
                    console.log(res)
                })
            })
        } else {
            const classroom = classrooms.filter(classroom => classroom.code === code)[0]
            setClassroom(classroom)
        }

        // Get all task data
        getAccessToken().then((accessToken) => {
            axios.get(process.env.NEXT_PUBLIC_BACKEND_HTTP_BASE+'core/tasks/', {
                headers: {'Authorization': 'Bearer '+accessToken},
                params: {'code': code}
            })
            .then(res => {
                console.log(res.data)
                setTasks(res.data)
            })
            .catch(res => {
                console.log(res)
            })
        })
    }, [router.query])

    useEffect(() => {
        if (!classroom) return

        // Get student profiles
        getAccessToken().then((accessToken) => {
            axios.get(process.env.NEXT_PUBLIC_BACKEND_HTTP_BASE+'core/student_profiles/', {
                headers: {'Authorization': 'Bearer '+accessToken},
                params: {'code': classroom.code}
            })
            .then(res => {
                setNames(res.data)
            })
        })
    }, [classroom])

    const changePage = () => {
        setIsDashboard(!isDashboard)
    }

    const changeStatus = () => {
        const newClassroom = {...classroom, status: !classroom.status ? 1 : 0}
        updateClassroom(newClassroom)
    }

    const removeIndex = (index) => {
        const newClassroom = {...classroom, student_indexes: classroom.student_indexes.filter(i => i !== parseInt(index))}
        updateClassroom(newClassroom)
    }

    const addStudent = () => {
        // New student will have the largest index number
        const newIndex = Math.max(...classroom.student_indexes)+1
        const newClassroom = {...classroom, student_indexes: [...classroom.student_indexes, newIndex]}
        setNames([...names, {index:newIndex, name:""}])
        updateClassroom(newClassroom)
    }

    const updateClassroom = (newClassroom) => {
        getAccessToken().then((accessToken) => {
            axios.put(process.env.NEXT_PUBLIC_BACKEND_HTTP_BASE+'core/classrooms/'+newClassroom.id+'/', newClassroom, {
                headers: {'Authorization': 'Bearer '+accessToken},
            })
            .then(res => {
                setClassroom(res.data)
                setClassrooms([...classrooms.filter(cr => cr.id !== res.data.id), res.data])
            })
        })
    }

    const updateName = (index, name) => {
        getAccessToken().then((accessToken) => {
            axios.put(process.env.NEXT_PUBLIC_BACKEND_HTTP_BASE+'core/student_profiles/'+classroom.id+'/', {
                code: classroom.code, index, name
            }, {
                headers: {'Authorization': 'Bearer '+accessToken},
            })
            .then(res => {
                setNames([...names.filter(n => n.index !== index), {index, name}])
            })
        })
    }

    return (
        <div>
            <Head>
                <title>Teacher | LMS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            { classroom && (
                <div className="flex sm:flex-row flex-col min-h-screen w-full">
                    <div className="pt-10 px-4">
                        <h1 className="text-3xl font-bold px-2">{classroom.name}</h1>
                        <p className={`${classroom.status ? "text-green-600" : "text-red-500"} px-2 mb-4 font-bold`}>{classroom.status ? 'Active' : 'Archived'}</p>
                        <button className={`${isDashboard ? "bg-gray-200" : "hover:bg-gray-200"} text-lg font-semibold px-2 py-1 my-1 w-full text-left rounded-lg`} onClick={changePage}>Dashboard</button>
                        <button className={`${(!isDashboard) ? "bg-gray-200" : "hover:bg-gray-200"} text-lg font-semibold px-2 py-1 my-1 w-full text-left rounded-lg`} onClick={changePage}>Settings</button>

                        <div className="flex flex-col mt-8 px-2 py-2 text-lg bg-black rounded-lg text-white">
                            <div><p className="text-base pb-1">Your class code is</p></div>
                            <div><p className="text-center py-1 font-mono bg-white text-black rounded">{classroom.code}</p></div>
                        </div>

                    </div>
                    <div className="bg-gray-100 w-full pt-8 px-8">
                        { isDashboard ?
                            <Dashboard
                                classroom={classroom} removeIndex={removeIndex}
                                addStudent={addStudent} names={names} updateName={updateName}
                                tasks={tasks} setTasks={setTasks}
                            /> :
                            <Settings classroom={classroom} changeStatus={changeStatus} />
                        }
                    </div>
                </div>
            )}

            <footer>
            </footer>
        </div>
    )
}

export default Classroom
