import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Home | LMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-4">
        <h1 className="text-7xl mb-8">LMS</h1>

        <Link href="/student"><button className="py-2 px-2 mb-4 bg-gray-500 rounded text-white">I am a student.</button></Link>
        <br />
        <Link href="/teacher"><button className="py-2 px-2 bg-gray-500 rounded text-white">I am a teacher.</button></Link>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
