import Head from 'next/head'
import { useEffect, useState, useContext } from 'react'
import { useRouter } from 'next/router'
import axios from 'axios'
import SyncLoader from "react-spinners/SyncLoader"

import { AuthContext } from '../contexts/Auth.Context'

const StudentLogin = () => {
    const router = useRouter()

    const {auth, setAuth} = useContext(AuthContext)
    const [code, setCode] = useState()
    const [index, setIndex] = useState()
    const [loginFailed, setLoginFailed] = useState()

    const [invalidInput, setInvalidInput] = useState(false)

    const loginUser = (e) => {
        e.preventDefault()
        // Validation
        if ((code.length !== 6) | (isNaN(index))) {
            setLoginFailed(true)
            return
        }

        setAuth({...auth, loading: true})

        console.log('ran')
        axios.post(process.env.NEXT_PUBLIC_BACKEND_HTTP_BASE+'auth/token/', {
            "username":code+'_'+index, "password":index
        }, { headers: {'Content-Type': 'application/json'}})
        .then(res => {
            setAuth({ loading: false, isAuthenticated: true, tokens: res.data, userType: "student" })
        })
        .catch(res => {
            console.log('login failed')
            setAuth({...auth, loading: false})
            setLoginFailed(true)
        })
    }

    useEffect(() => {
        if (auth.isAuthenticated) router.push('/student/')
    }, [auth])

    return (
        <div>
            <Head>
                <title>Login | LMS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center pt-8 px-8 bg-white">
                { invalidInput && <p className="py-2 px-2 border-2 border-red-500 rounded-lg font-bold text-red-500">Invalid inputs.</p>}

                <h1 className="text-5xl my-6 font-bold">Join Classroom</h1>

                <form onSubmit={e => loginUser(e)} className="">
                    <label>
                        <h2 className="font-semibold text-lg pb-0.5">Classroom Code</h2>
                        <input className="outline-none border-b-2 text-3xl" type="text" name="code" onChange={e => setCode(e.target.value)} autocomplete="off" />
                    </label>
                    <label>
                        <h2 className="font-semibold text-lg pt-4 pb-0.5">Index</h2>
                        <input className="outline-none border-b-2 text-3xl" type="text" name="index" onChange={e => setIndex(e.target.value)} autocomplete="off" />
                    </label>
                    <br />
                    { loginFailed && <small className="text-red-500 mt-2">Invalid username or password.</small>}
                    { auth.loading ? (
                        <div className="flex flex-row justify-center bg-blue-500 mt-4 py-1 px-2 rounded-md w-full" style={{height: "36px"}}>
                            <SyncLoader color={"#ffffff"} size={8} margin={1} />
                        </div>
                    ) : (
                        <button type="submit" className="bg-blue-500 hover:bg-blue-600 text-white text-lg mt-4 py-1 px-2 rounded-md w-full">Join</button>
                    )}
                </form>
            </main>

            <footer>
            </footer>
        </div>
    )
}

export default StudentLogin
